x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.10.3
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"},{"variables":[],"name":"clean"}]'
      SESSION_COOKIE_SECURE: "on"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  frontend:
    image: redpencil/frontend-linked.toerismevlaanderen.be:1.6.0-fastboot
    links:
      - identifier:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  database:
    image: semtech/sparql-parser:0.0.14
    volumes:
      - ./config/authorization/:/config/
      - ./data/authorization/:/data/
    restart: "always"
    labels:
      - "logging=true"
    logging: *default-logging
  triplestore:
    image: redpencil/virtuoso:1.3.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    volumes:
      - ./data/db:/data
      - ./config/db/virtuoso.ini:/data/virtuoso.ini
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  delta-notifier:
    image: semtech/mu-delta-notifier:0.4.0
    volumes:
        - ./config/delta:/config
    logging: *default-logging
    restart: always
    labels:
      - "logging=true"
  migrations:
    image: semtech/mu-migrations-service:0.9.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  login:
    image: semtech/mu-login-service:3.0.0
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  registration:
    image: semtech/mu-registration-service:2.7.3
    entrypoint: echo "Only needed for mu script"
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: "no"
    logging: *default-logging
    labels:
      - "logging=true"
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource:
    image: semtech/mu-cl-resources:1.26.0
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  import:
    image: redpencil/logies-data-converter-service:1.4.0
    volumes:
      - ./data/input:/input
      - ./data/output:/output
      - ./data/files:/share
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  dataset-generator:
    image: redpencil/logies-dataset-generator-service:0.5.0
    volumes:
      - ./data/files:/share
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  file:
    image: semtech/mu-file-service:3.4.0
    volumes:
      - ./data/files:/share
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  uri-info:
    image: redpencil/mu-uri-info-service:0.2.1
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource-labels-cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource-labels:backend
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
  resource-labels:
    image: lblod/resource-label-service:0.3.2
    environment:
      DEFAULT_LANGUAGE: "nil"
    restart: always
    logging: *default-logging
    labels:
      - "logging=true"
