version: '3.4'

services:
  identifier:
    image: semtech/mu-identifier:1.5.0
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
  database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  resource:
    image: semtech/mu-cl-resources:1.17.1
    volumes:
      - ./config/resources:/config
