version: '3.4'

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"

services:
  identifier:
    image: semtech/mu-identifier:1.10.0
    environment:
      DEFAULT_MU_AUTH_ALLOWED_GROUPS_HEADER: '[{"variables":[],"name":"public"},{"variables":[],"name":"clean"}]'
    restart: always
    logging: *default-logging
  dispatcher:
    image: semtech/mu-dispatcher:2.1.0-beta.2
    volumes:
      - ./config/dispatcher:/config
    restart: always
    logging: *default-logging
  frontend:
    image: redpencil/frontend-linked.toerismevlaanderen.be:1.3.0-fastboot
    links:
      - identifier:backend
    restart: always
    logging: *default-logging
  database:
    image: semtech/mu-authorization:0.6.0-beta.7
    environment:
      MU_SPARQL_ENDPOINT: "http://triplestore:8890/sparql"
      DATABASE_COMPATIBILITY: "Virtuoso"
      DATABASE_OVERLOAD_RECOVERY: "on"
    volumes:
      - ./config/authorization:/config
    restart: always
    logging: *default-logging
  triplestore:
    image: redpencil/virtuoso:1.0.0
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/graphs/public"
    volumes:
      - ./data/db:/data
      - ./config/db/virtuoso.ini:/data/virtuoso.ini
    restart: always
    logging: *default-logging
  delta-notifier:
    image: semtech/mu-delta-notifier:0.1.0
    volumes:
        - ./config/delta:/config
    logging: *default-logging
    restart: always
  migrations:
    image: semtech/mu-migrations-service:0.7.0
    links:
      - triplestore:database
    volumes:
      - ./config/migrations:/data/migrations
    restart: always
    logging: *default-logging
  login:
    image: semtech/mu-login-service:3.0.0
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: always
    logging: *default-logging
  registration:
    image: semtech/mu-registration-service:2.7.3
    entrypoint: echo "Only needed for mu script"
    environment:
      USERS_GRAPH: "http://mu.semte.ch/graphs/users"
      SESSIONS_GRAPH: "http://mu.semte.ch/graphs/sessions"
    restart: "no"
    logging: *default-logging
  cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource:backend
    restart: always
    logging: *default-logging
  resource:
    image: semtech/mu-cl-resources:1.21.1
    environment:
      CACHE_CLEAR_PATH: "http://cache/.mu/clear-keys"
    volumes:
      - ./config/resources:/config
    restart: always
    logging: *default-logging
  import:
    image: redpencil/logies-data-converter-service:1.0.0
    volumes:
      - ./data/input:/input
      - ./data/output:/output
      - ./data/files:/share
    restart: always
    logging: *default-logging
  dataset-generator:
    image: redpencil/logies-dataset-generator-service:0.2.1
    volumes:
      - ./data/files:/share
    restart: always
    logging: *default-logging
  file:
    image: semtech/mu-file-service:3.1.2
    volumes:
      - ./data/files:/share
    restart: always
    logging: *default-logging
  uri-info:
    image: redpencil/mu-uri-info-service:0.2.1
    restart: always
    logging: *default-logging
  resource-labels-cache:
    image: semtech/mu-cache:2.0.2
    links:
      - resource-labels:backend
    restart: always
    logging: *default-logging
  resource-labels:
    image: lblod/resource-label-service:0.3.2
    environment:
      DEFAULT_LANGUAGE: "nil"
    restart: always
    logging: *default-logging
