version: '3.4'

services:
  frontend:
    image: redpencil/frontend-linked.toerismevlaanderen.be
    links:
      - identifier:backend
  identifier:
    image: semtech/mu-identifier:1.5.0
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
  database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  cache:
    image: semtech/mu-cache:0.6.0
    links:
      - resource:backend
  resource:
    image: semtech/mu-cl-resources:1.17.1
    volumes:
      - ./config/resources:/config
  file:
    image: semtech/mu-file-service:3.1.0
    volumes:
      - ./data/files:/share
