version: '3.4'

services:
  identifier:
    ports:
      - 80:80
  frontend:
    environment:
      EMBER_FASTBOOT_HOST: "localhost"
  triplestore:
    ports:
      - "8890:8890"
  database:
    environment:
      LOG_OUTGOING_SPARQL_QUERIES: "true"
  cache:
    environment:
      LOG_CACHE_KEYS: "true"
      LOG_CLEAR_KEYS: "true"
