version: '3.4'

services:
  frontend:
    image: redpencil/frontend-linked.toerismevlaanderen.be
    links:
      - identifier:backend
      - yasgui:sparqlui
  openapi-ui-proxy:
    image: redpencil/openapi-ui-proxy
    links:
      - identifier:backend
      - swagger:swagger
    volumes:
      - ./data/openapi:/data
  swagger:
    image: swaggerapi/swagger-ui:v3.20.5
    environment:
      - "API_URL=/openapi/openapi.json"
      - "PORT=80"
  identifier:
    image: semtech/mu-identifier:1.5.0
  dispatcher:
    image: semtech/mu-dispatcher:1.1.2
    volumes:
      - ./config/dispatcher:/config
  yasgui:
    image: erikap/yasgui
    ports:
      - "9999:80"
    environment:
      DEFAULT_SPARQL_ENDPOINT: "http://linked.toerismevlaanderen.be/sparql"
  sparql:
    image: semtech/mu-authorization:0.2.0
    environment:
      MU_SPARQL_ENDPOINT: "http://database:8890/sparql"
    volumes:
      - ./config/authorization:/config
  database:
    image: tenforce/virtuoso:1.3.2-virtuoso7.2.2
    environment:
      SPARQL_UPDATE: "true"
      DEFAULT_GRAPH: "http://mu.semte.ch/application"
    volumes:
      - ./data/db:/data
  cache:
    image: semtech/mu-cache:0.6.0
    links:
      - resource:backend
  resource:
    image: semtech/mu-cl-resources:1.17.1
    volumes:
      - ./config/resources:/config
  file:
    image: semtech/mu-file-service:3.1.0
    volumes:
      - ./data/files:/share
