(in-package :mu-cl-resources)

(add-prefix "schema" "http://schema.org/")
(add-prefix "dct" "http://purl.org/dc/terms/")
(add-prefix "skos" "http://www.w3.org/2004/02/skos/core#")
(add-prefix "adms" "http://www.w3.org/ns/adms#")
(add-prefix "locn" "http://www.w3.org/ns/locn#")
(add-prefix "prov" "http://www.w3.org/ns/prov#")
(add-prefix "wgs" "http://www.w3.org/2003/01/geo/wgs84_pos#")
(add-prefix "generiek" "https://data.vlaanderen.be/ns/generiek#")
(add-prefix "adres" "https://data.vlaanderen.be/ns/adres#")
(add-prefix "organisatie" "https://data.vlaanderen.be/ns/organisatie#")
(add-prefix "logies" "https://data.vlaanderen.be/ns/logies#")
(add-prefix "geosparql" "http://www.opengis.net/ont/geosparql#")
(add-prefix "foaf" "http://xmlns.com/foaf/0.1/")
(add-prefix "vcard" "http://www.w3.org/2006/vcard/ns#")
(add-prefix "regorg" "http://www.w3.org/ns/regorg#")
(add-prefix "nfo" "http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#")
(add-prefix "nie" "http://www.semanticdesktop.org/ontologies/2007/01/19/nie#")
(add-prefix "dbpedia" "http://dbpedia.org/ontology/")
(add-prefix "mu" "http://mu.semte.ch/vocabularies/core/")
(add-prefix "ext" "http://mu.semte.ch/vocabularies/ext/")
